# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
build_and_test: # this can be any name you choose
  executor: python/default
  steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Run tests
        command: python -m pytest tests.py
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
